name: Release Charts

on:
  push:
    tags:
    - v*

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set chart version and app versions
        run: |
          RELEASE_VERSION=$( echo $GITHUB_REF | sed -nE 's!refs/tags/!!p' | cut -c 2- )
          sed -i '/version/d' ./chart/Chart.yaml
          echo "appVersion: $RELEASE_VERSION" >> ./chart/Chart.yaml
          echo "version: $RELEASE_VERSION" >> ./chart/Chart.yaml
          cat ./chart/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts
          skip_existing: false